name: Waka Readme Stats

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上8点运行

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # 刚刚在 Secrets 中设置的 Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # GitHub 会自动处理这个 Token，无需设置
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 下面是显示内容的配置，可以按需调整
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          # 让布局更紧凑
          LAYOUT: "compact"
